// Données initiales du Trombinoscope
// Chaque profil peut être enrichi/modifié depuis l'interface
// Les noms ont été dérivés des handles Instagram et peuvent être édités

export const SEED_PROFILES = [
  // ===================== STYLISTES =====================
  // Le champ "professions" est un array — un profil peut avoir plusieurs métiers.
  { instagram: 'victoiresimonney',     name: 'Victoire Simonney',      professions: ['Styliste'] },
  { instagram: 'charlesbeugniot',      name: 'Charles Beugniot',        professions: ['Styliste'] },
  { instagram: 'sinabraetz',           name: 'Sina Braetz',             professions: ['Styliste'] },
  { instagram: 'ohcharlz',             name: 'Charlz',                  professions: ['Styliste'] },
  { instagram: 'sarah_lespagnol',      name: 'Sarah Lespagnol',         professions: ['Styliste'] },
  { instagram: 'paulinerobinboniface', name: 'Pauline Robin-Boniface',  professions: ['Styliste'] },
  { instagram: 'faymahoulame',         name: 'Fay Mahoulame',           professions: ['Styliste'] },
  { instagram: 'claudia.c.cali',       name: 'Claudia C. Cali',         professions: ['Styliste'] },
  { instagram: 'alyseehenot',          name: 'Alysée Henot',            professions: ['Styliste'] },
  { instagram: 'jeanlougignx',         name: 'Jean-Lou Gignx',          professions: ['Styliste'] },
  { instagram: 'louis_portejoie',      name: 'Louis Portejoie',         professions: ['Styliste'] },
  { instagram: 'rbsalome',             name: 'Salomé RB',               professions: ['Styliste'] },
  { instagram: 'floredesermet',        name: 'Flore de Sermet',         professions: ['Styliste'] },
  { instagram: 'leoniemauchant',       name: 'Léonie Mauchant',         professions: ['Styliste'] },
  { instagram: 'margueritegrandin',    name: 'Marguerite Grandin',      professions: ['Styliste'] },
  { instagram: 'andrea_colace',        name: 'Andrea Colace',           professions: ['Styliste'] },
  { instagram: 'diane.serfati',        name: 'Diane Serfati',           professions: ['Styliste'] },
  { instagram: 'chiaraficola',         name: 'Chiara Ficola',           professions: ['Styliste'] },
  { instagram: 'celeste___andre',      name: 'Céleste André',           professions: ['Styliste'] },
  { instagram: 'noemiebeltran',        name: 'Noémie Beltran',          professions: ['Styliste'] },
  { instagram: 'agatheauriffeille',    name: 'Agathe Auriffeille',      professions: ['Styliste'] },
  { instagram: 'selfina_33',           name: 'Selfina',                 professions: ['Styliste'] },

  // ===================== RÉALISATEURS =====================
  { instagram: 'omrirosengart',        name: 'Omri Rosengart',          professions: ['Réalisateur'] },
  { instagram: 'wangave',              name: 'Wang Avé',                professions: ['Réalisateur'] },
  { instagram: 'mizh_u',               name: 'Mizh U',                  professions: ['Réalisateur'] },
  { instagram: 'jeremiedanon',         name: 'Jérémie Danon',           professions: ['Réalisateur'] },
  { instagram: 'lokma.ne',             name: 'Lokmane',                 professions: ['Réalisateur'] },
  { instagram: 'pauzklop',             name: 'Pauz Klop',               professions: ['Réalisateur'] },
  { instagram: 'raphaelstora',         name: 'Raphaël Stora',           professions: ['Réalisateur'] },
  { instagram: 'hugocohen',            name: 'Hugo Cohen',              professions: ['Réalisateur'] },
  { instagram: 'sarsz',                name: 'Sarsz',                   professions: ['Réalisateur'] },
  { instagram: 'demi_chat',            name: 'Demi Chat',               professions: ['Réalisateur'] },
  { instagram: 'renaud.labelle',       name: 'Renaud Labelle',          professions: ['Réalisateur'] },
  { instagram: 'tomkleinberg',         name: 'Tom Kleinberg',           professions: ['Réalisateur'] },
  { instagram: 'heintzpaul',           name: 'Paul Heintz',             professions: ['Réalisateur'] },
  { instagram: 'leilamac',             name: 'Leila Mac',               professions: ['Réalisateur'] },
  { instagram: 'schaubiz',             name: 'Schaubiz',                professions: ['Réalisateur'] },
  { instagram: 'vitali_akimov',        name: 'Vitali Akimov',           professions: ['Réalisateur'] },
  { instagram: 'baloji',               name: 'Baloji',                  professions: ['Réalisateur'] },
  { instagram: 'naiacombary',          name: 'Naia Combary',            professions: ['Réalisateur'] },
  { instagram: 'ojoz',                 name: 'Ojoz',                    professions: ['Réalisateur'] },
  { instagram: 'alixbortoli',          name: 'Alix Bortoli',            professions: ['Réalisateur'] },
  { instagram: 'pierre.boissel',       name: 'Pierre Boissel',          professions: ['Réalisateur'] },
  { instagram: 'kidhao',               name: 'Kid Hao',                 professions: ['Réalisateur'] },
  { instagram: 'antoine_zago_h',       name: 'Antoine Zago H',          professions: ['Réalisateur'] },
  { instagram: 'nathan_ghali',         name: 'Nathan Ghali',            professions: ['Réalisateur'] },
  { instagram: 'juanawein_',           name: 'Juana Wein',              professions: ['Réalisateur'] },
  { instagram: 'david_camarou',        name: 'David Camarou',           professions: ['Réalisateur'] },
  { instagram: 'camus_valat',          name: 'Camus Valat',             professions: ['Réalisateur'] },
  { instagram: 'alexrash__',           name: 'Alex Rash',               professions: ['Réalisateur'] },
  { instagram: '2tiret',               name: '2tiret',                  professions: ['Réalisateur'] },
  { instagram: 'shadenadela',          name: 'Shaden Adela',            professions: ['Réalisateur'] },
  { instagram: 'leonardvernhet',       name: 'Léonard Vernhet',         professions: ['Réalisateur'] },
];

// Liste des métiers proposés (extensible depuis l'UI via le champ "profession")
export const PROFESSIONS = [
  'Styliste',
  'Réalisateur',
  'Photographe',
  'Maquilleur·se',
  'Coiffeur·se',
  'Directeur·rice artistique',
  'Chef opérateur',
  'Cadreur',
  'Ingénieur du son',
  'Monteur·se',
  'Étalonneur·se',
  'Producteur·rice',
  'Régisseur·se',
  'Décorateur·rice',
  'Mannequin',
  'Casting',
  'Storyboarder',
  'Scénariste',
  'Compositeur',
  'Motion designer',
  'Retoucheur·se',
  'Assistant·e',
  'Autre',
];

// Statuts de relation
export const STATUSES = [
  { id: 'a_contacter',   label: 'À contacter',     color: '#9ca3af' },
  { id: 'en_cours',      label: 'En discussion',   color: '#f59e0b' },
  { id: 'collabore',     label: 'Déjà collaboré',  color: '#10b981' },
  { id: 'favori',        label: 'Favori',          color: '#ef4444' },
];
