// Données initiales du Trombinoscope
// Chaque profil peut être enrichi/modifié depuis l'interface
// Les noms ont été dérivés des handles Instagram et peuvent être édités

export const SEED_PROFILES = [
  // ===================== STYLISTES =====================
  { instagram: 'victoiresimonney',     name: 'Victoire Simonney',      profession: 'Styliste' },
  { instagram: 'charlesbeugniot',      name: 'Charles Beugniot',        profession: 'Styliste' },
  { instagram: 'sinabraetz',           name: 'Sina Braetz',             profession: 'Styliste' },
  { instagram: 'ohcharlz',             name: 'Charlz',                  profession: 'Styliste' },
  { instagram: 'sarah_lespagnol',      name: 'Sarah Lespagnol',         profession: 'Styliste' },
  { instagram: 'paulinerobinboniface', name: 'Pauline Robin-Boniface',  profession: 'Styliste' },
  { instagram: 'faymahoulame',         name: 'Fay Mahoulame',           profession: 'Styliste' },
  { instagram: 'claudia.c.cali',       name: 'Claudia C. Cali',         profession: 'Styliste' },
  { instagram: 'alyseehenot',          name: 'Alysée Henot',            profession: 'Styliste' },
  { instagram: 'jeanlougignx',         name: 'Jean-Lou Gignx',          profession: 'Styliste' },
  { instagram: 'louis_portejoie',      name: 'Louis Portejoie',         profession: 'Styliste' },
  { instagram: 'rbsalome',             name: 'Salomé RB',               profession: 'Styliste' },
  { instagram: 'floredesermet',        name: 'Flore de Sermet',         profession: 'Styliste' },
  { instagram: 'leoniemauchant',       name: 'Léonie Mauchant',         profession: 'Styliste' },
  { instagram: 'margueritegrandin',    name: 'Marguerite Grandin',      profession: 'Styliste' },
  { instagram: 'andrea_colace',        name: 'Andrea Colace',           profession: 'Styliste' },
  { instagram: 'diane.serfati',        name: 'Diane Serfati',           profession: 'Styliste' },
  { instagram: 'chiaraficola',         name: 'Chiara Ficola',           profession: 'Styliste' },
  { instagram: 'celeste___andre',      name: 'Céleste André',           profession: 'Styliste' },
  { instagram: 'noemiebeltran',        name: 'Noémie Beltran',          profession: 'Styliste' },
  { instagram: 'agatheauriffeille',    name: 'Agathe Auriffeille',      profession: 'Styliste' },
  { instagram: 'selfina_33',           name: 'Selfina',                 profession: 'Styliste' },

  // ===================== RÉALISATEURS =====================
  { instagram: 'omrirosengart',        name: 'Omri Rosengart',          profession: 'Réalisateur' },
  { instagram: 'wangave',              name: 'Wang Avé',                profession: 'Réalisateur' },
  { instagram: 'mizh_u',               name: 'Mizh U',                  profession: 'Réalisateur' },
  { instagram: 'jeremiedanon',         name: 'Jérémie Danon',           profession: 'Réalisateur' },
  { instagram: 'lokma.ne',             name: 'Lokmane',                 profession: 'Réalisateur' },
  { instagram: 'pauzklop',             name: 'Pauz Klop',               profession: 'Réalisateur' },
  { instagram: 'raphaelstora',         name: 'Raphaël Stora',           profession: 'Réalisateur' },
  { instagram: 'hugocohen',            name: 'Hugo Cohen',              profession: 'Réalisateur' },
  { instagram: 'sarsz',                name: 'Sarsz',                   profession: 'Réalisateur' },
  { instagram: 'demi_chat',            name: 'Demi Chat',               profession: 'Réalisateur' },
  { instagram: 'renaud.labelle',       name: 'Renaud Labelle',          profession: 'Réalisateur' },
  { instagram: 'tomkleinberg',         name: 'Tom Kleinberg',           profession: 'Réalisateur' },
  { instagram: 'heintzpaul',           name: 'Paul Heintz',             profession: 'Réalisateur' },
  { instagram: 'leilamac',             name: 'Leila Mac',               profession: 'Réalisateur' },
  { instagram: 'schaubiz',             name: 'Schaubiz',                profession: 'Réalisateur' },
  { instagram: 'vitali_akimov',        name: 'Vitali Akimov',           profession: 'Réalisateur' },
  { instagram: 'baloji',               name: 'Baloji',                  profession: 'Réalisateur' },
  { instagram: 'naiacombary',          name: 'Naia Combary',            profession: 'Réalisateur' },
  { instagram: 'ojoz',                 name: 'Ojoz',                    profession: 'Réalisateur' },
  { instagram: 'alixbortoli',          name: 'Alix Bortoli',            profession: 'Réalisateur' },
  { instagram: 'pierre.boissel',       name: 'Pierre Boissel',          profession: 'Réalisateur' },
  { instagram: 'kidhao',               name: 'Kid Hao',                 profession: 'Réalisateur' },
  { instagram: 'antoine_zago_h',       name: 'Antoine Zago H',          profession: 'Réalisateur' },
  { instagram: 'nathan_ghali',         name: 'Nathan Ghali',            profession: 'Réalisateur' },
  { instagram: 'juanawein_',           name: 'Juana Wein',              profession: 'Réalisateur' },
  { instagram: 'david_camarou',        name: 'David Camarou',           profession: 'Réalisateur' },
  { instagram: 'camus_valat',          name: 'Camus Valat',             profession: 'Réalisateur' },
  { instagram: 'alexrash__',           name: 'Alex Rash',               profession: 'Réalisateur' },
  { instagram: '2tiret',               name: '2tiret',                  profession: 'Réalisateur' },
  { instagram: 'shadenadela',          name: 'Shaden Adela',            profession: 'Réalisateur' },
  { instagram: 'leonardvernhet',       name: 'Léonard Vernhet',         profession: 'Réalisateur' },
];

// Liste des métiers proposés (extensible depuis l'UI via le champ "profession")
export const PROFESSIONS = [
  'Styliste',
  'Réalisateur',
  'Photographe',
  'Maquilleur·se',
  'Coiffeur·se',
  'Directeur·rice artistique',
  'Chef opérateur',
  'Cadreur',
  'Ingénieur du son',
  'Monteur·se',
  'Étalonneur·se',
  'Producteur·rice',
  'Régisseur·se',
  'Décorateur·rice',
  'Mannequin',
  'Casting',
  'Storyboarder',
  'Scénariste',
  'Compositeur',
  'Motion designer',
  'Retoucheur·se',
  'Assistant·e',
  'Autre',
];

// Statuts de relation
export const STATUSES = [
  { id: 'a_contacter',   label: 'À contacter',     color: '#9ca3af' },
  { id: 'en_cours',      label: 'En discussion',   color: '#f59e0b' },
  { id: 'collabore',     label: 'Déjà collaboré',  color: '#10b981' },
  { id: 'favori',        label: 'Favori',          color: '#ef4444' },
];
